Creating domain models
luckyDucky3/PetFamily pull request #3
Opened 2024-12-30 17:11 UTC by luckyDucky3

2024-12-30 17:57 UTC, luckyDucky3 commented
Все старался выполнять согласно условиям (возможно некоторые свойства также следовало бы представить как Value Objects, но пока помимо тех что указаны в задании и телефонного номера не знаю, что можно представить как VO еще.)
Создал enum для Status класса Pet

2024-12-31 10:37 UTC, KirillSachkov requested changes

2024-12-31 10:37 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +public class Pet : Entity<Guid>
нужно ещё добавить конструктор публичный через который ты создашь Pet

2024-12-31 10:37 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ValueObjects/SpeciesBreeds.cs
> +    public Guid SpeciesID { get; }
Вместо ID просто Id, иначе нарушение наименования

2024-12-31 10:37 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ValueObjects/SpeciesBreeds.cs
> +    public SpeciesBreeds(Guid speciesID, Guid breedID)
здесь тоже

2024-12-31 11:19 UTC, luckyDucky3 commented
Все недочеты исправил

2024-12-31 12:35 UTC, KirillSachkov approved these changes

2024-12-31 16:30 UTC, merged